import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Your Pal Collective",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav>
					<ul className="globalNav">
						<li>About</li>
						<li>How it works</li>
						<li>Impact</li>
						<li>Get involved</li>
						<li>FAQs</li>
						<li>Contact us</li>
					</ul>
				</nav>
				{children}
			</body>
		</html>
	)
}
